# 使用说明 V4.2.0
# 1. 使用docker-compose  宿主机不需要配置host来发现
# 2. 无需修改源码，根目录  docker-compose up 即可
# 3. 静静等待服务启动

version: '3'
services:
  test-web:
    build:
      context: .
    restart: always
    container_name: test-web
    image: test-web
    ports:
      - 8099:8099
